xxl:
  job:
    admin:
      addresses: http://192.168.179.124:8093/xxl-job-admin
      accessToken: default_token
      timeout: 3
    executor:
      appname: zhuyue-taobao-job-executor
      address:
      ip:
      port: 7979
      logpath: .\logs
      logretentiondays: 30