# 配置网址url相关的参数
url:
  tvUrl: # 电视剧
    https://movie.douban.com/j/search_subjects?type=tv&tag=%E7%83%AD%E9%97%A8&page_limit=50&page_start=0
  movieUrl:
    https://movie.douban.com/j/search_subjects?type=movie&tag=%E7%83%AD%E9%97%A8&page_limit=50&page_start=0
  # mainUrl: https://movie.douban.com/j/search_subjects?






